  # Play1 - Setting up k8s
  - name: Setting up k8s
    hosts: localhost

    tasks:
    
      - name: Create lsfs namespace
        k8s:
          kubeconfig: "~/.kube/config"
          name: lsfs
          api_version: v1
          kind: Namespace
          state: present
