   # Play1 - Collecting nodes info (Node name and Ips)
  - name: Collenting nodes info
    hosts: localhost

    vars: 
      peer_host_group_name: peers
      client_host_group_name: clients

    tasks:

      - name: Collect nodes IP addresses
        shell: | 
                kubectl get nodes -o wide --no-headers | awk '{ print $1 ,$7}'
        register: nodesIPs

      - set_fact:
          peer_nodes: []
          client_nodes: []

      - set_fact:
          peer_nodes: "{{ peer_nodes + [{ 'name': name , 'ip' : ip }] }}"
        vars: 
          name: "{{ item.split(' ').0 }}"
          ip: "{{ item.split(' ').1 }}"
        with_items: "{{ nodesIPs.stdout_lines }}"
        when: name is search("peer-nodes")

      - set_fact:
          client_nodes: "{{ client_nodes + [{ 'name': name , 'ip' : ip }] }}"
        vars: 
          name: "{{ item.split(' ').0 }}"
          ip: "{{ item.split(' ').1 }}"
        with_items: "{{ nodesIPs.stdout_lines }}"
        when: name is search("client-nodes")

      - name: Add peer nodes as hosts
        add_host:
          hostname: '{{ item.ip }}'
          ansible_user: '{{ hosts_user }}'
          groups:
          - "{{ peer_host_group_name }}"
        with_items: "{{ peer_nodes }}"

      - name: Add client nodes as hosts
        add_host:
          hostname: '{{ item.ip }}'
          ansible_user: '{{ hosts_user }}'
          groups:
          - "{{ client_host_group_name }}"
        with_items: "{{ client_nodes }}"

      - name: Write hosts to file
        template:
          src: "hosts_template.j2"
          dest: "hosts"

  # Play2 - Setting up nodes
  - name: Send configuration file to node
    hosts: peers, clients
    tasks:

      - name: Creates shared dir
        file:
          path: ~/shared_dir
          state: directory

      - name: Put Config File in Shared (Volume) directory
        copy:
          src: ~/Mestrado/5ano/daniel-LSFS/LSFS/conf.yaml
          dest: "~/shared_dir/conf.yaml"
