
  - name: Creation of bootstrapper Pod
    hosts: localhost
    roles:
      - bootstrapper

  - name: Creation of Peer Pods
    hosts: localhost
    roles:
      - { role: peers, nr_peers: 10, bootstrapper_ip: "{{ boot_ip }}", mount_dir: "/home/{{ hosts_user }}/shared_dir" }
    vars:
      boot_ip: "{{ hostvars['localhost']['bootstrapper_ip'] }}"


  - name: Wait until peers creation
    hosts: localhost
    tasks:
      - name: Pause for 2 minutes until all peers are created
        pause:
          minutes: 2

  - name: Creation of client Pods
    hosts: localhost
    roles:
      - { role: clients, nr_clients: 1, bootstrapper_ip: "{{ boot_ip }}", mount_dir: "/home/{{ hosts_user }}/shared_dir" }
    vars:
      boot_ip: "{{ hostvars['localhost']['bootstrapper_ip'] }}"