---
- name: Install requirements for package install
  apt:
    update_cache: yes
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
  when: python3_pyenv == None
  become: true
  register: apt_pyenv
  retries: 1000
  until: apt_pyenv is success


- name: Install system packages required for pyenv
  apt:
    update_cache: yes
    name:
      - curl
      - gcc
      - git
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - make
      - zlib1g-dev
    state: present
  when: python3_pyenv != None
  become: true
  register: apt_system
  retries: 1000
  until: apt_system is success
