# Play1 -Clean peer database
  - name: Clean leveldb files
    hosts: masters, workers
    tasks:

      - name: Clean peers database
        become: yes
        file:
          path: /home/{{ ansible_user }}/{{ remote_com_directory }}/levelDB/
          state: absent
        