 # Play1 -Clean shared directory
  - name: Clean shared directory previous deploy files
    hosts: masters, workers
    tasks:
        
      - name: Clean peer ips file
        become: yes
        file:
          path: /home/{{ ansible_user }}/{{ remote_com_directory }}/peer_ips
          state: absent

      # - name: Clean metrics files
      #   become: yes
      #   file:
      #     path: /home/{{ ansible_user }}/{{ remote_com_directory }}/metrics
      #     state: absent

      - name: Clean workloads files
        become: yes
        file:
          path: /home/{{ ansible_user }}/{{ remote_com_directory }}/workloads-filebench
          state: absent

      - name: Clean config file
        become: yes
        file:
          path: /home/{{ ansible_user }}/{{ remote_com_directory }}/conf.yaml"
          state: absent