---

- name: Start monitoring on client node
  hosts: client
  tasks:
    - name: Create log directory
      file:
        path: "/home/{{ ansible_user }}/logs/{{ run_name }}"
        state: directory
        mode: '0755'
    - name: remove previous same name monitoring files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/{{ ansible_user }}/logs/{{ run_name }}/dstat-{{ ansible_date_time.date }}.csv"
        - "/home/{{ ansible_user }}/logs/{{ run_name }}/iostat-{{ ansible_date_time.date }}.csv"
    - name: Start dstat
      shell:
        #cmd: dstat --time --cpu --mem --disk --swap -D nvme0n1 --output $run_name/dstat-$DATE.csv > /dev/null &
        cmd: "dstat --time --cpu --mem --disk --swap -D sda --output dstat-{{ ansible_date_time.date }}.csv > /dev/null &"
        chdir: "/home/{{ ansible_user }}/logs/{{ run_name }}"
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0
    - name: Start iostat
      shell:
        cmd: "sh {{ resources_dir }}/iostat-csv/iostat-csv.sh > iostat-{{ ansible_date_time.date }}.csv &"
        chdir: "/home/{{ ansible_user }}/logs/{{ run_name }}"
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0
    # - shell: start nvidia-smi
    #     cmd: "sh {{ resources_dir }}/iostat-csv/iostat-csv.sh > {{ run_name }}/iostat-{{ ansible_date_time.date }}.csv &"
    #     chdir: "/home/{{ ansible_user }}/logs/{{ run_name }}"
    #   async: 2592000               # 60*60*24*30 – 1 month
    #   poll: 0

- name: Start monitoring on peers node
  hosts: peer, bootstrapper, master
  tasks:
    - name: Create log directory
      file:
        path: "/home/{{ ansible_user }}/logs/{{ run_name }}"
        state: directory
        mode: '0755'
    - name: remove previous same name monitoring files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/{{ ansible_user }}/logs/{{ run_name }}/dstat-{{ ansible_date_time.date }}.csv"
        - "/home/{{ ansible_user }}/logs/{{ run_name }}/iostat-{{ ansible_date_time.date }}.csv"
    - name: Copy iostat script file to remote server
      copy:
        src: iostat-csv.sh
        dest: "/home/{{ ansible_user }}/iostat-csv.sh"
    - name: Start dstat
      shell:
        cmd: "dstat --time --cpu --mem --disk --swap -D sda --output dstat-{{ ansible_date_time.date }}.csv > /dev/null &"
        chdir: "/home/{{ ansible_user }}/logs/{{ run_name }}"
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0
    - name: Start iostat
      shell:
        cmd: "sh /home/{{ ansible_user }}/iostat-csv.sh > iostat-{{ ansible_date_time.date }}.csv &"
        chdir: "/home/{{ ansible_user }}/logs/{{ run_name }}"
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0