---

- name: Install necessary packages
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
   - build-essential
   - autoconf
   - libtool
   - pkg-config
   - apt-utils
   - automake 
   - libtool 
   - bison 
   - flex
   - git

- name: Clone filebench repository
  git:
    repo: https://github.com/filebench/filebench.git
    dest: /home/{{ ansible_user_id }}/filebench

- name: Install filebench
  shell:
    cmd: 'alias yacc="bison" && libtoolize && aclocal && 
      autoheader && automake --add-missing && autoconf && 
      ./configure && make && make install'
    chdir: /home/{{ ansible_user_id }}/filebench

- name: Remove filebench directory
  file:
    path: /home/{{ ansible_user_id }}/filebench
    state: absent