- name: Install google-auth python module
  pip:
    name: google-auth

- name: Install boto python module
  pip:
    name: boto

- name: Install unzip
  become: yes
  apt:
    name: unzip
    state: present

- name: Install libffi-dev (need for tensorflow)
  become: yes
  apt:
    name: libffi-dev
    state: present

- name: Install basel dependent pkgs
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg

- name: Add an Apt signing key, uses whichever key is at the URL
  become: yes
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    state: present

- name: Add basel repository
  become: yes
  apt_repository:
    filename: bazel.list
    repo: deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
    state: present


- name: update apt list
  become: yes
  apt:
    update_cache: yes

- name: Install basel (need for tensorflow)
  become: yes  
  apt:
    name: bazel
    state: present

- name: Download from bucket
  gc_storage:
    bucket: "lsfs-bucket"
    object: "tensorflow.zip"
    dest: "/home/{{ ansible_user }}/tensorflow.zip"
    mode: get
    gs_access_key: GOOGG44PCMOLPIORPWXFILV2
    gs_secret_key: F8sh0E3Hq7gV8QlxWQ0dKonc/1LCW6qpljbCH++T
  ignore_errors: yes

- name: Extract tensorflow zip
  unarchive:
    src: "/home/{{ ansible_user }}/tensorflow.zip"
    dest: "/home/{{ ansible_user }}/"
    remote_src: yes

- name: Remove tensorflow zip
  file:
    path: "/home/{{ ansible_user }}/tensorflow.zip"
    state: absent

- name: Replace home dir name
  replace:
    path: "/home/{{ ansible_user }}/tensorflow/train-official-model.sh"
    regexp: '/home/[^/]+/'
    replace: '/home/{{ ansible_user }}/'

- name: Extract model tar
  unarchive:
    src: "/home/{{ ansible_user }}/tensorflow/models/official-models-2.1.0.tar.gz"
    dest: "/home/{{ ansible_user }}/tensorflow/models/"
    remote_src: yes

- name: Remove file model tar file
  file:
    path: "/home/{{ ansible_user }}/tensorflow/models/official-models-2.1.0.tar.gz"
    state: absent