---

- name: copy build files to remote host
  copy:
    src: images_build/
    dest: /home/

- name: install pip module
  shell: "apt install python3-pip -y"

- name: install docker-py
  pip:
    name: docker-py

- name: Log into DockerHub
  docker_login:
    username: lsfsusertemp
    password: Lsfs123User456Temp.,;

- shell: "docker pull lsfsusertemp/lsfs-testing:bootstrapper"

- shell: "docker pull lsfsusertemp/lsfs-testing:peer"

- shell: "docker pull lsfsusertemp/lsfs-testing:client"

    #- name: Pull base image
    #  docker_image:
    #    name: lsfs-testing:lsfs
    #    source: pull

#- name: Build base image
#  docker_image:
#    name: cpp-build-base:0.1.0
#    # dockerfile: /home/build_base
#    build:
#      path: /home/build_base
#    state: present
#    source: build

#- name: Build bootstrapper image
#  docker_image:
#    name: bootstrapper:0.1.0
#    # dockerfile: /home/build_bootstrapper
#    build:
#      path: /home/build_bootstrapper
#    state: present
#    source: build

#- name: Build peer image
#  docker_image:
#    name: peer:0.1.0
#    # dockerfile: /home/build_peer
#    build:
#      path: /home/build_peer
#    state: present
#    source: build

#- name: Build client image
#  docker_image:
#    name: client:0.1.0
#    # dockerfile: /home/build_client
#    build:
#      path: /home/build_client
#    state: present
#    source: build
