
  # Play1 - Cleaning dbs
  - name: Cleaning db from every peers
    hosts: workers
    become: yes

    tasks:

      - name: Remove db files
        file:
          path: /home/{{ hosts_user }}/lsfs/shared_dir/levelDB
          state: absent

