---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: us-east1-b
        gcp_region: us-east1
        gcp_project: dflasks
        gcp_cred_kind: serviceaccount
        gcp_cred_file: credentials.json
        gcp_account_email: 'lsfs-deploy@dflasks.iam.gserviceaccount.com'
        gcp_account_scope: 'https://www.googleapis.com/auth/cloud-platform'
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20200414
        disks:
          - { name: disk-01, disk_size: 12 } #master
          - { name: disk-02, disk_size: 200 } #node
        addresses:
          - addr-01
          - addr-02
        instances:
          - { index: 1,tags: [master, kube-cluster], gcp_machine_type: n1-standard-2 }
          - { index: 2, tags: [node, kube-cluster], gcp_machine_type: n1-standard-1 }

- hosts: [master, node]
  become: yes
  roles:
    - { role: users, payload: users.yml }

- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - role: image-build
    - role: fuse

#- hosts: master
#  gather_facts: yes
#  become: yes
#  tasks:
#     - name: "Helm role"
#       include_role:
#         name: helm
#       when: "additional_features.helm"
#       run_once: yes
#       tags: helm

#     - name: "MetalLB role"
#       include_role:
#         name: metallb
#       when: "additional_features.metallb"
#       run_once: yes
#       tags: metallb

#     - name: "Healthcheck role"
#       include_role:
#         name: healthcheck
#       when: "additional_features.healthcheck"
#       run_once: yes
#       tags: healthcheck
