
- name: Create Client Pod
  k8s:
    kubeconfig: "/home/{{ hosts_user }}/.kube/config"
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/client_pod.yml.j2') }}"
    validate:
      fail_on_error: yes
  with_items:
    - "{{ range(1, nr_clients + 1) | list }}"

# Only works with pod
# - name: Wait until client pod is created
#   k8s_info:
#     kubeconfig: "/home/{{ hosts_user }}/.kube/config"
#     namespace: lsfs
#     api_version: v1
#     name: "client{{ item }}"
#     kind: Pod
#   register: client_pod
#   retries: 10
#   until: client_pod.resources[0].status.phase == "Running"
#   with_items:
#     - "{{ range(1, nr_clients + 1) | list }}"


# - name: Run command necessary for filebench workloads
#   kubernetes.core.k8s_exec:
#     kubeconfig: "/home/{{ hosts_user }}/.kube/config"
#     namespace: lsfs
#     pod: "client{{ item }}"
#     command: echo 0 > /proc/sys/kernel/randomize_va_space
#   with_items:
#     - "{{ range(1, nr_clients + 1) | list }}"