apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: lsfs
  labels:
    lsfs: client
spec:
  containers:
  - name: client-container
    image: brancc0cdocker/lsfs-client
    command: ["./build/lsfs_exe"]
    args: ["127.0.0.1", "1", "conf.yaml", "client1", "test_filesystem/InnerFolder", "test_filesystem/InnerFolder2"]
  ports: 
    - containerPort: 12357
    - containerPort: 12358
