- name: Create Client Pod
  k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config" #/home/danielsf97/.kube/config
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/client.yml.j2') }}"
#      apiVersion: v1
#      kind: Pod
#      metadata:
#        name: client
#        namespace: lsfs
#      spec:
#        containers:
#        - name: client-container
#          image: lsfsusertemp/lsfs-testing:client
#          command: [ "/bin/sh", "-c", "while true; do sleep 3600; done" ]
#          #command: ["./build/lsfs_exe", "{{ bootstrapper_ip }}", "{{ client_id }}", "scripts/conf.yaml", "/P2P-Filesystem/Teste/InnerFolder/", "/P2P-Filesystem/Teste/InnerFolder2/"]
#          args: ["--privileged", "--cap-add", "SYS_ADMIN", "--device", "/dev/fuse"]
#          #- "--privileged  --cap-add SYS_ADMIN --device /dev/fuse"
#        #- containerPort: 12345
#        #- containerPort: 12346

