# Play1 -Setup single_node directory and workloads
  - name: Setup config and workload files
    hosts: masters
    become: yes

    vars: 
        remote_dir: /home/{{ ansible_user }}/{{ remote_com_directory }}

    tasks:

      - name: Creates shared_dir
        file:
          path: "{{ remote_dir }}"
          state: directory
      
      - name: Put Config File in single_node directory
        copy:
          src: ../conf.yaml
          dest: "{{ remote_dir }}/conf.yaml"

      - name: Creates workloads dir
        file:
          path: "{{ remote_dir }}/workloads-filebench"
          state: directory

      - name: Put workloads in single_node directory
        copy:
          src: ../../workloads-filebench/
          dest: "{{ remote_dir }}/workloads-filebench/"

      - name: Creates dstat scripts dir
        file:
          path: "{{ remote_dir }}/dstat"
          state: directory

      - name: Put dstat scripts in single_node directory
        copy:
          src: ../../../dstat/
          dest: "{{ remote_dir }}/dstat/"


      - name: Creates metrics dir
        file:
          path: "{{ remote_dir }}/metrics"
          state: directory