# Play1 - Initiate container and processes
  - name: Initiate container and processes
    hosts: masters
    become: yes

    tasks:

      - name: Pull lsfs container image
        docker_image:
          name: "{{ image_name }}"
          source: pull

      - name: Create docker container with pseudo-tty
        shell: | 
                docker run --privileged --volume=/home/{{ ansible_user }}/{{ remote_com_directory }}:/{{ container_com_directory }} --name lsfs_local -t -d {{ image_name }}

      - name: Exec bootstrapper process
        shell: | 
                docker exec -d lsfs_local ./build/bootstrapper_exe /{{ container_com_directory }}/conf.yaml

      - name: Exec peer1 process
        shell: | 
                docker exec -d lsfs_local ./build/peer_exe 1 0.75 /{{ container_com_directory }}/conf.yaml 127.0.0.1 12365 12366 12367 -n

      - name: Exec peer2 process
        shell: | 
                docker exec -d lsfs_local ./build/peer_exe 2 0.25 /{{ container_com_directory }}/conf.yaml 127.0.0.1 12368 12369 12370 -n

      - name: Pause for 60 seconds until peer is started
        pause:
          seconds: 60

      - name: Get pid to be killed
        shell: | 
                docker exec lsfs_local ps aux | grep "peer_exe 1" | awk '{ print $2 }' | head -n 1
        register: pid_to_kill

      - name: kill unused process
        shell: |
                docker exec lsfs_local kill -9 {{ pid_to_kill.stdout }}


      - name: Exec client process
        shell: | 
                docker exec -d lsfs_local ./build/lsfs_exe 127.0.0.1 1 /{{ container_com_directory }}/conf.yaml client1 /test_filesystem/InnerFolder /test_filesystem/InnerFolder2
