---

- name: Create Peer Pod
  when: free_database|bool == false
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/peer.yml.j2') }}"
  with_together:
    - "{{ nodes_id }}"
    - "{{ nodes_pos }}"
    - "{{ machine_nrs }}"

- name: Create Peer Pod delete database
  when: free_database|bool == true
  k8s:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/peer_clear_dbs.yml.j2') }}"
  with_together:
    - "{{ nodes_id }}"
    - "{{ nodes_pos }}"
    - "{{ machine_nrs }}"