---

- name: get name of leveldb inner directories
  find:
    paths: "/home/{{ ansible_user }}/share-dir/levelDB"
    use_regex: yes
    patterns: '^.*[0-9]+$'
    recurse: no
    file_type: directory
  register: find_result

- name: get node_id based on database name
  set_fact:
    node_id: "{{ find_result.files[0].path | regex_replace('^(.*)/([0-9]+)$', '\\2')}}"

- name: print find_result
  debug: var=node_id

- name: Compress peer database directory
  archive:
    path: "/home/{{ ansible_user }}/share-dir/levelDB"
    dest: "/home/{{ ansible_user }}/share-dir/{{ node_id }}.zip"
    format: zip

# - name: create a object
#   gcp_storage_object:
#     action: upload
#     bucket: lsfs_bucket
#     src: "/home/{{ ansible_user }}/share-dir/{{ node_id }}.gz"
#     dest: "{{ node_id }}.gz"
#     project: lsfs-283710
#     auth_kind: serviceaccount
#     service_account_file: "{{ service_account_file }}"
#     state: present
#     overwrite: yes

- name: Upload to bucket
  gc_storage:
    bucket: "lsfs_bucket"
    object: "{{ node_id }}.zip"
    src: "/home/{{ ansible_user }}/share-dir/{{ node_id }}.zip"
    mode: put
    gs_access_key: GOOGG44PCMOLPIORPWXFILV2
    gs_secret_key: F8sh0E3Hq7gV8QlxWQ0dKonc/1LCW6qpljbCH++T
  ignore_errors: yes

- name: Remove database archive file
  file:
    path: "/home/{{ ansible_user }}/share-dir/{{ node_id }}.zip"
    state: absent
