---
# tasks file for sysctl

- name: set sysctl rules
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    ignoreerrors: "{{ sysctl_ignore_errors }}"
  with_dict: "{{ sysctl_rules }}"
  when: sysctl_rules is defined
  tags: [sysctl]