- name: GCP Teardown
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    gcp_network_name: lsfs-network
    gcp_subnet_name: subnet-us-east-192
    gcp_router_name: nat-router
    gcp_subnet_range: 192.168.0.0/16
    gcp_zone: us-east1-d
    gcp_region: us-east1
    gcp_project: lsfs-283710
    gcp_cred_kind: serviceaccount
    gcp_cred_file: credentials.json
    network_name: lsfs-network
  tasks:
    - name: get info on an instance
      gcp_compute_instance_info:
        zone: "{{ gcp_zone }}"
        filters:
        - name != instance-test-runner-0001
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: output

    - name: Remove Nat Router
      shell: "{{ item }}"
      with_items:
        - "gcloud compute --project {{ gcp_project }} routers delete {{ gcp_router_name }} --region {{ gcp_region }}"

    - name: Remove Internal firewall rules
      gcp_compute_firewall:
        name: "internal-rules"
        network: 
          selfLink: "projects/{{ gcp_project }}/global/networks/{{ gcp_network_name }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent

    - name: Remove Internal/external firewall rules
      gcp_compute_firewall:
        name: "internal-external-rules"
        network: 
          selfLink: "projects/{{ gcp_project }}/global/networks/{{ gcp_network_name }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent

    - name: Teardown instances
      gcp_compute_instance:
        name: "{{ item.name }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent
      loop: "{{ output['resources'] }}"
      async: 300
      poll: 5

    - name: Delete subnetwork
      gcp_compute_subnetwork:
        name: "{{ gcp_subnet_name }}"
        region: "{{ gcp_region }}"
        network:
          selfLink: "projects/{{ gcp_project }}/global/networks/{{ gcp_network_name }}"
        ip_cidr_range: "{{ gcp_subnet_range }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent

    - name: Delete network
      gcp_compute_network:
        name: "{{ gcp_network_name }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: absent
