# Play - Run workload
  - name: Run Workload + start and stop dstat
    hosts: masters

    tasks:

      - name: Start dstat in all peer pods
        shell: | 
                kubectl exec -n lsfs peer{{ item }} -- bash /{{ com_directory }}/scripts/init_dstat.sh {{ metrics_path }} peer run-{{ wl_name }}-lsfs-fb.dstat.csv
        with_items:
          - "{{ range(1, nr_peers | int + 1) | list }}"
        

      - name: Start dstat in client pods
        shell: | 
                kubectl exec -n lsfs client1 -- bash /{{ com_directory }}/scripts/init_dstat.sh {{ metrics_path }} client run-{{ wl_name }}-lsfs-fb.dstat.csv
        

      - name: Start filebench workload on clients
        shell: | 
                kubectl exec -it -n lsfs client1 -- /bin/bash -c "filebench -f /home/{{ansible_user}}/{{ wl_path }}" &>> /home/{{ ansible_user }}/{{ output_file_path }}


      - name: Stop dstat in all peers
        shell: | 
                kubectl exec -n lsfs peer{{ item }} -- bash /{{ com_directory }}/scripts/stop_dstat.sh &> /dev/null
        with_items:
          - "{{ range(1, nr_peers | int + 1) | list }}"


      - name: Stop dstat in clients
        shell: | 
                kubectl exec -n lsfs client1 -- bash /{{ com_directory }}/scripts/stop_dstat.sh &> /dev/null
       
        
