---
- name: create a cluster
  gcp_container_cluster:
    name: "{{ gkename }}"
    master_auth:
      username: "{{ username }}"
      password: "{{ password }}"
    initial_node_count: "{{ initial_node_count }}"
    node_config:
      image_type: "{{ image_type }}"
      machine_type: "{{ machine_type }}"
      disk_size_gb: "{{ disk_size_gb }}"
      preemptible: "{{ preemptible }}"
    zone: "{{ zone }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: present
  register: cluster

#- name: create a node pool
#  gcp_container_node_pool:
#    name: "{{ npname }}"
#    initial_node_count: "{{ initial_node_count }}"
#    cluster: "{{ cluster }}"
#    config:
#      disk_size_gb: "{{ disk_size_gb }}"
#      image_type: "{{ image_type }}"
#      machine_type: "{{ machine_type }}"
#      preemptible: "{{ preemptible }}"
#    zone: "{{ zone }}"
#    project: "{{ project }}"
#    auth_kind: "{{ auth_kind }}"
#    service_account_file: "{{ service_account_file }}"
#    scopes:
#      - https://www.googleapis.com/auth/cloud-platform
#    state: present
