# Play - Run workload
  - name: Start monitoring with dstat
    hosts: masters

    tasks:

      - name: Start dstat in all peer pods
        shell: | 
                kubectl exec -n lsfs peer{{ item }} -- bash /{{ container_com_directory }}/dstat/init_dstat.sh /{{ container_com_directory }}/metrics run-{{ wl_name }}-lsfs-peer{{ item }}.dstat.csv
        with_items:
          - "{{ range(1, nr_peers | int + 1) | list }}"
        

      - name: Start dstat in client pods
        shell: | 
                kubectl exec -n lsfs client1 -- bash /{{ container_com_directory }}/dstat/init_dstat.sh /{{ container_com_directory }}/metrics run-{{ wl_name }}-lsfs-client1.dstat.csv


  - name: Start monitoring gpu
    hosts: clients

    tasks:

      - name: Start Nvidia-smi if Gpu present
        shell:
          cmd: "sudo nvidia-smi --query-gpu=timestamp,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv -l 1 -f nvidia-smi-{{ wl_name }}.csv &"
          chdir: "/home/{{ ansible_user }}/{{ remote_com_directory }}/metrics"
        async: 2592000               # 60*60*24*30 – 1 month
        poll: 0