---

- name: get name of leveldb inner directories
  find:
    paths: "/home/{{ ansible_user }}/share-dir/levelDB"
    use_regex: yes
    patterns: '^.*[0-9]+$'
    recurse: no
    file_type: directory
  register: find_result

- name: get node_id based on database name
  set_fact:
    node_id: "{{ find_result.files[0].path | regex_replace('^(.*)([0-9]+)$', '\\2')}}"

- name: Download from bucket
  gc_storage:
    bucket: "lsfs_bucket"
    object: "{{ node_id }}.zip"
    dest: "/home/{{ ansible_user }}/share-dir/{{ node_id }}.zip"
    mode: get
    gs_access_key: GOOGG44PCMOLPIORPWXFILV2
    gs_secret_key: F8sh0E3Hq7gV8QlxWQ0dKonc/1LCW6qpljbCH++T
  ignore_errors: yes

- name: Remove previous database folder
  become: true
  file:
    path: "/home/{{ ansible_user }}/share-dir/levelDB"
    state: absent

- name: Extract database archieve
  unarchive:
    remote_src: yes
    src: /home/{{ ansible_user }}/share-dir/1.zip
    dest: /home/{{ ansible_user }}/share-dir/

- name: Remove database archive file
  file:
    path: /home/{{ ansible_user }}/share-dir/{{ node_id }}.zip
    state: absent
