---
# vars file for sysctl

sysctl_rules:
  net.ipv4.neigh.default.gc_thresh1: 30000
  net.ipv4.neigh.default.gc_thresh2: 32000
  net.ipv4.neigh.default.gc_thresh3: 32768

  net.ipv6.neigh.default.gc_thresh1: 30000
  net.ipv6.neigh.default.gc_thresh2: 32000
  net.ipv6.neigh.default.gc_thresh3: 32768