churn_conf_type: constant|manual_configuration|off
constant:
  churn_interval: 1
  churn_op_type: add|remove|random|alternate
  percentage: 10
  num_target_peers: 5
manual_configuration:
  - time_min: 2
    churn_op_type: add|remove|random
    percentage: 10
    num_target_peers: 5
  - time_min: 5
    churn_op_type: add|remove|random
    percentage: 10
    num_target_peers: 5
  