# Play - Run workload
  - name: Run Workload + start and stop dstat
    hosts: masters
    become: yes

    tasks:
     
      - name: Start filebench workload
        shell: | 
                docker exec passthrough filebench -f /{{ wl_path }}
        register: 
              filebench_output

      - name: Setting filebench output fact
        set_fact:
          fb_output: "{{ filebench_output.stdout }}"
        delegate_to: localhost
        delegate_facts: true

     

  # Play - Collecting filebench output
  - name: Collenting filebench output
    hosts: localhost

    tasks:

        - name: write output filebench 
          shell: | 
                echo "{{ hostvars['localhost']['fb_output'] }}" >> ../{{ output_path }}
