 # Play1 -Setup shared directory and workloads
  - name: Setup config and workload files
    hosts: masters, workers
    tasks:

      - name: Creates shared dir
        file:
          path: /home/{{ ansible_user }}/shared_dir
          state: directory
      
      - name: Creates database dir
        file:
          path: /home/{{ ansible_user }}/shared_dir/levelDB
          state: directory

      - name: Put Config File in Shared (Volume) directory
        copy:
          src: ../conf.yaml
          dest: "/home/{{ ansible_user }}/shared_dir/conf.yaml"

      - name: Creates workloads dir
        file:
          path: /home/{{ ansible_user }}/shared_dir/workloads-filebench
          state: directory

      - name: Put workloads in Shared (Volume) directory
        copy:
          src: ../../workloads-filebench/
          dest: "/home/{{ ansible_user }}/shared_dir/workloads-filebench/"

      - name: Creates dstat scripts dir
        file:
          path: /home/{{ ansible_user }}/shared_dir/dstat
          state: directory

      - name: Put dstat scripts in Shared (Volume) directory
        copy:
          src: ../../../dstat/
          dest: "/home/{{ ansible_user }}/shared_dir/dstat/"
