 # Play1 -Setup shared directory and workloads
  - name: Setup config and workload files
    hosts: masters, workers
    become: yes

    vars: 
        remote_dir: /home/{{ ansible_user }}/{{ remote_com_directory }}

    tasks:

      - name: Creates shared dir
        file:
          path: "{{ remote_dir }}"
          state: directory

      - name: Creates mount dir
        file:
          path: "/home/{{ ansible_user }}/{{ remote_mount_vol_directory }}"
          state: directory

      - name: Creates mount inner dir
        file:
          path: "/home/{{ ansible_user }}/{{ remote_mount_vol_directory }}/InnerFolder"
          state: directory
      
      - name: Creates mount inner backend dir
        file:
          path: "/home/{{ ansible_user }}/{{ remote_mount_vol_directory }}/InnerFolder2"
          state: directory
      
      - name: Creates database dir
        file:
          path: "{{ remote_dir }}/levelDB"
          state: directory

      - name: Put Config File in Shared (Volume) directory
        copy:
          src: ../conf.yaml
          dest: "{{ remote_dir }}/conf.yaml"

      - name: Creates workloads dir
        file:
          path: "{{ remote_dir }}/workloads-filebench"
          state: directory

      - name: Put workloads in Shared (Volume) directory
        copy:
          src: ../../workloads-filebench/
          dest: "{{ remote_dir }}/workloads-filebench/"

      - name: Creates dstat scripts dir
        file:
          path: "{{ remote_dir }}/dstat"
          state: directory

      - name: Put dstat scripts in Shared (Volume) directory
        copy:
          src: ../../../dstat/
          dest: "{{ remote_dir }}/dstat/"
