# Play - Run workload
  - name: Run Workload + start and stop dstat
    hosts: masters

    tasks:

      - name: Start dstat in all peer pods
        shell: | 
                kubectl exec -n lsfs peer{{ item }} -- bash /{{ com_directory }}/dstat/init_dstat.sh {{ metrics_path }} peer{{ item }} run-{{ wl_name }}-lsfs-fb.dstat.csv
        with_items:
          - "{{ range(1, nr_peers | int + 1) | list }}"
        

      - name: Start dstat in client pods
        shell: | 
                kubectl exec -n lsfs client1 -- bash /{{ com_directory }}/dstat/init_dstat.sh {{ metrics_path }} client run-{{ wl_name }}-lsfs-fb.dstat.csv
        

      - name: Start filebench workload on clients
        shell: | 
                kubectl exec -n lsfs client1 -- /bin/bash -c "filebench -f /{{ wl_path }}" 
        register: 
              filebench_output

      - name: Setting filebench output fact
        set_fact:
          fb_output: "{{ filebench_output.stdout }}"
        delegate_to: localhost
        delegate_facts: true


      - name: Stop dstat in all peers
        shell: | 
                kubectl exec -n lsfs peer{{ item }} -- bash /{{ com_directory }}/dstat/stop_dstat.sh &> /dev/null
        with_items:
          - "{{ range(1, nr_peers | int + 1) | list }}"


      - name: Stop dstat in clients
        shell: | 
                kubectl exec -n lsfs client1 -- bash /{{ com_directory }}/dstat/stop_dstat.sh &> /dev/null
       


  # Play - Collecting filebench output
  - name: Collenting filebench output
    hosts: localhost

    tasks:

        - name: write output filebench 
          shell: | 
                echo "{{ hostvars['localhost']['fb_output'] }}" >> {{ output_path }}

