# Play - Run workload
  - name: Run Workload + start and stop dstat
    hosts: masters

    tasks:

      - name: Start dstat in all peer pods
        shell: | 
                kubectl exec -n lsfs peer{{ item }} -- bash /{{ container_com_directory }}/dstat/init_dstat.sh /{{ container_com_directory }}/metrics run-{{ wl_name }}-lsfs-peer{{ item }}.dstat.csv
        with_items:
          - "{{ range(1, nr_peers | int + 1) | list }}"
        when: dstat_peer_config is defined
        

      - name: Start dstat in client pods
        shell: | 
                kubectl exec -n lsfs client1 -- bash /{{ container_com_directory }}/dstat/init_dstat.sh /{{ container_com_directory }}/metrics run-{{ wl_name }}-lsfs-client1.dstat.csv
        when: dstat_client_config is defined

      - name: Start filebench workload on clients
        shell: | 
                kubectl exec -n lsfs client1 -- /bin/bash -c "filebench -f /{{ wl_path }}" 
        register: 
              filebench_output

      - name: Setting filebench output fact
        set_fact:
          fb_output: "{{ filebench_output.stdout }}"
        delegate_to: localhost
        delegate_facts: true


      - name: Stop dstat in all peers
        shell: | 
                kubectl exec -n lsfs peer{{ item }} -- bash /{{ container_com_directory }}/dstat/stop_dstat.sh &> /dev/null
        with_items:
          - "{{ range(1, nr_peers | int + 1) | list }}"
        when: dstat_peer_config is defined


      - name: Stop dstat in clients
        shell: | 
                kubectl exec -n lsfs client1 -- bash /{{ container_com_directory }}/dstat/stop_dstat.sh &> /dev/null
        when: dstat_client_config is defined


  # Play - Collecting filebench output
  - name: Collenting filebench output
    hosts: localhost

    tasks:

        - name: write output filebench 
          shell: | 
                echo "{{ hostvars['localhost']['fb_output'] }}" >> ../{{ output_path }}


  # Play - Collecting dstat output
  - name: Collenting dstat output
    hosts: masters, workers
    become: yes

    tasks:

        - name: Copy peers dstat output to local
          fetch:
            src: /home/{{ ansible_user }}/{{ remote_com_directory }}/metrics/run-{{ wl_name }}-lsfs-peer{{ item }}.dstat.csv
            dest: ../{{ dstat_path }}/
            flat: yes
            fail_on_missing: no
          with_items:
            - "{{ range(1, nr_peers | int + 1) | list }}"
          when: dstat_peer_config is defined

        - name: Copy client dstat output to local
          fetch:
            src: /home/{{ ansible_user }}/{{ remote_com_directory }}/metrics/run-{{ wl_name }}-lsfs-client1.dstat.csv
            dest: ../{{ dstat_path }}/
            flat: yes
            fail_on_missing: no
          when: dstat_client_config is defined