# Play - Run workload
  - name: Zip leveldb files
    hosts: worker1

    vars: 
        remote_dir: /home/{{ ansible_user }}/lsfs/shared_dir/levelDB

    tasks:

      - name: Zip all file groups
        shell: | 
                cd {{ remote_dir }}/ && sudo zip -r {{ item }}.zip {{ item }}_deleted/ {{ item }} {{ item }}_tmp_anti_entropy/
                cd {{ remote_dir }}/ && sudo rm -r {{ item }}_deleted/ {{ item }} {{ item }}_tmp_anti_entropy/
        with_items:
          - "{{ range(1, nr_groups | int + 1) | list }}"



#!/bin/bash

for i in $(seq 1 500); do kubectl patch node peer$i -p '{"spec":{"podCIDR":"10.244.0.0/16"}}'; done