---

- name: Install Python3
  become: yes
  apt:
    update_cache: yes
    name: python3.6
    state: latest
  register: apt_python3
  retries: 1000
  until: apt_python3 is success

- name: Install Python3 Pip
  become: yes
  apt:
    name: python3-pip
    state: latest
  register: apt_python3_pip
  retries: 1000
  until: apt_python3_pip is success

- name: Install Ansible
  become: yes
  pip:
    name: ansible

- name: Install necessary pip modules
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - google-auth
    - boto
    - regex
    - numpy
    - apache-libcloud
    - pause
    - psutil

- name: Download unzip package
  become: yes
  apt:
    name: unzip
  register: apt_unzip
  retries: 1000
  until: apt_unzip is success

- name: Download from bucket
  gc_storage:
    bucket: "lsfs_bucket"
    object: "/Deploy.zip"
    dest: "/home/{{ ansible_user }}/Deploy.zip"
    mode: get
    gs_access_key: GOOGG44PCMOLPIORPWXFILV2
    gs_secret_key: F8sh0E3Hq7gV8QlxWQ0dKonc/1LCW6qpljbCH++T
  ignore_errors: yes

- name: Extract Deploy archieve
  unarchive:
    remote_src: yes
    src: "/home/{{ ansible_user }}/Deploy.zip"
    dest: "/home/{{ ansible_user }}/"

- name: Remove Deploy archive file
  file:
    path: "/home/{{ ansible_user }}/Deploy.zip"
    state: absent

